ALTER TABLE users
DROP COLUMN username,
ALTER COLUMN email TYPE VARCHAR(100),
ADD COLUMN first_name VARCHAR(100),
ADD COLUMN last_name VARCHAR(100),
ADD COLUMN password VARCHAR(255),
ADD COLUMN img_url VARCHAR(255),
ADD COLUMN description TEXT,
ADD COLUMN is_available BOOLEAN DEFAULT true,
ADD COLUMN avg_score DECIMAL(3,2) DEFAULT 0,
ADD COLUMN reviews_count INTEGER DEFAULT 0,
ADD COLUMN is_vendor BOOLEAN DEFAULT false,
ADD COLUMN working_hours JSONB,
ADD COLUMN is_mobile_vendor BOOLEAN;

ALTER TABLE users
ALTER COLUMN first_name SET NOT NULL,
ALTER COLUMN last_name SET NOT NULL,
ALTER COLUMN password SET NOT NULL,
ADD CONSTRAINT users_email_unique UNIQUE (email);
